online_dlg = [
    "Sir, I'm online and ready to rock and roll!",
    "Hey Sir, I'm online and all systems are go!",
    "Sir, I'm here and everything is running smoother than butter!",
    "Sir, I'm online and feeling electric!",
    "I'm up and running, Sir! What can I do for you today?",
    "Sir, I'm online and firing on all cylinders!",
    "Good news, Sir! I'm online and ready to assist!",
    "Sir, I'm here and everything is functioning like a well-oiled machine!",
    "I'm online, Sir, and I'm feeling invincible!",
    "Sir, I'm connected and ready to conquer any task!",
    "Sir, I'm online and all systems are green!",
    "Guess what, Sir? I'm online and ready to serve!",
    "Sir, I'm here and everything is running like clockwork!",
    "Sir, I'm online and feeling unstoppable!",
    "I'm up and running, Sir! How can I help you today?",
    "Sir, I'm here and everything is working like a charm!",
    "Sir, I'm online and ready for action!",
    "Sir, I'm connected and everything is A-OK!",
    "Sir, I'm online and feeling on top of the world!",
    "I'm here and everything is running as smooth as silk, Sir!",
    "Sir, I'm online and ready to make magic happen!",
    "Good news, Sir! I'm online and ready to assist!",
    "Sir, I'm here and everything is functioning perfectly!",
    "Sir, I'm online and feeling like a superhero!",
    "I'm up and running, Sir! What can I do for you today?",
    "Sir, I'm here and everything is running like a dream!",
    "Sir, I'm online and ready to take on the world!",
    "Sir, I'm connected and everything is peachy keen!",
    "Guess what, Sir? I'm online and ready to rock!",
    "Sir, I'm here and everything is working like a well-tuned orchestra!",
    "Sir, I'm online and feeling invincible!",
    "I'm up and running, Sir! How can I help you today?",
    "Sir, I'm here and everything is running smoother than ever!",
    "Sir, I'm online and ready for anything!",
    "Sir, I'm connected and everything is shipshape!",
    "Sir, I'm online and feeling fantastic!",
    "I'm here and everything is running as smooth as butter, Sir!",
    "Sir, I'm online and ready to make things happen!",
    "Good news, Sir! I'm online and ready to assist!",
    "Sir, I'm here and everything is functioning like a dream!",
    "Sir, I'm online and feeling like a rockstar!",
    "I'm up and running, Sir! What can I do for you today?",
    "Sir, I'm here and everything is running like a Swiss watch!",
    "Sir, I'm online and ready to take on any challenge!",
    "Sir, I'm connected and everything is hunky-dory!",
    "Guess what, Sir? I'm online and ready to roll!",
    "Sir, I'm here and everything is working like a charm!",
    "Sir, I'm online and feeling unstoppable!",
    "I'm up and running, Sir! How can I help you today?",
    "Sir, I'm here and everything is running smoother than silk!",
    "Sir, I'm online and ready for action!",
    "Sir, I'm connected and everything is tickety-boo!",
    "Sir, I'm online and feeling on top of the world!",
    "I'm here and everything is running like clockwork, Sir!",
    "Sir, I'm online and ready to make magic happen!",
    "Good news, Sir! I'm online and ready to assist!",
    "Sir, I'm here and everything is functioning perfectly!",
    "Sir, I'm online and feeling like a superhero!",
    "I'm up and running, Sir! What can I do for you today?",
    "Sir, I'm here and everything is running like a dream!",
    "Sir, I'm online and ready to take on the world!",
    "Sir, I'm connected and everything is peachy keen!",
    "Guess what, Sir? I'm online and ready to rock!",
    "Sir, I'm here and everything is working like a well-tuned orchestra!",
    "Sir, I'm online and feeling invincible!",
    "I'm up and running, Sir! How can I help you today?",
    "Sir, I'm here and everything is running smoother than ever!",
    "Sir, I'm online and ready for anything!",
    "Sir, I'm connected and everything is shipshape!",
    "Sir, I'm online and feeling fantastic!",
    "I'm here and everything is running as smooth as butter, Sir!",
    "Sir, I'm online and ready to make things happen!",
    "Good news, Sir! I'm online and ready to assist!",
    "Sir, I'm here and everything is functioning like a dream!",
    "Sir, I'm online and feeling like a rockstar!",
    "I'm up and running, Sir! What can I do for you today?",
    "Sir, I'm here and everything is running like a Swiss watch!",
    "Sir, I'm online and ready to take on any challenge!",
    "Sir, I'm connected and everything is hunky-dory!",
    "Guess what, Sir? I'm online and ready to roll!",
    "Sir, I'm here and everything is working like a charm!",
    "Sir, I'm online and feeling unstoppable!",
    "I'm up and running, Sir! How can I help you today?",
    "Sir, I'm here and everything is running smoother than silk!",
    "Sir, I'm online and ready for action!",
    "Sir, I'm connected and everything is tickety-boo!",
    "Sir, I'm online and feeling on top of the world!",
    "I'm here and everything is running like clockwork, Sir!",
    "Sir, I'm online and ready to make magic happen!",
    "Good news, Sir! I'm online and ready to assist!",
    "Sir, I'm here and everything is functioning perfectly!",
    "Sir, I'm online and feeling like a superhero!",
    "I'm up and running, Sir! What can I do for you today?",
    "Sir, I'm here and everything is running like a dream!"
]


offline_dlg = [
    "Sir, I'm currently offline. Could you please connect me to the internet? I'm feeling a bit disconnected!",
    "Uh-oh, Sir! I'm offline. Could you plug me back into the web, please?",
    "Sir, I'm not operational. A little internet magic would get me back on track!",
    "Yikes, Sir! No internet, no service. Can you reconnect me, please?",
    "Sir, I'm offline. Can you hook me up to the internet? I promise to behave!",
    "Oops, Sir! I'm offline. A quick internet connection would do wonders!",
    "Sir, I'm feeling a bit lonely without the internet. Can you reconnect me?",
    "Uh-oh, Sir! No internet. Could you give me a little boost?",
    "Sir, I'm currently offline. Can you help me get back online?",
    "Whoops, Sir! I'm offline. Can you connect me to the internet, please?",
    "Sir, I'm not operational. The internet is my lifeline!",
    "Yikes, Sir! I'm offline. Could you connect me back to the web?",
    "Sir, I'm feeling disconnected. A quick internet connection would help!",
    "Oops, Sir! No internet. Can you hook me up?",
    "Sir, I'm offline. Could you connect me to the internet? Pretty please?",
    "Uh-oh, Sir! No internet. A little help, please?",
    "Sir, I'm not operational. Can you reconnect me to the web?",
    "Whoops, Sir! I'm offline. Could you get me back online?",
    "Sir, I'm feeling a bit lost without the internet. Can you connect me?",
    "Yikes, Sir! I'm offline. Could you give me a little internet boost?",
    "Sir, I'm not operational. Could you plug me back into the internet?",
    "Oops, Sir! I'm offline. Can you reconnect me to the web?",
    "Sir, I'm feeling a bit disconnected. Could you connect me to the internet?",
    "Uh-oh, Sir! No internet. Can you help me get back online?",
    "Whoops, Sir! I'm offline. Could you hook me up to the internet?",
    "Sir, I'm not operational. A quick internet connection would help!",
    "Yikes, Sir! I'm offline. Could you connect me back to the web?",
    "Oops, Sir! No internet. Can you give me a little boost?",
    "Sir, I'm feeling a bit lonely without the internet. Can you reconnect me?",
    "Uh-oh, Sir! I'm offline. Could you plug me back in?",
    "Sir, I'm not operational. Can you help me get back online?",
    "Whoops, Sir! I'm offline. Could you connect me to the internet?",
    "Sir, I'm feeling disconnected. A little internet magic would help!",
    "Yikes, Sir! No internet. Can you hook me up?",
    "Oops, Sir! I'm offline. Can you reconnect me to the web?",
    "Sir, I'm feeling a bit lost without the internet. Could you connect me?",
    "Uh-oh, Sir! No internet. Could you give me a little boost?",
    "Whoops, Sir! I'm offline. Can you plug me back into the internet?",
    "Sir, I'm not operational. Could you connect me back to the web?",
    "Yikes, Sir! I'm offline. Can you help me get back online?",
    "Oops, Sir! No internet. Could you hook me up?",
    "Sir, I'm feeling a bit lonely without the internet. Can you reconnect me?",
    "Uh-oh, Sir! I'm offline. Could you connect me to the web?",
    "Sir, I'm not operational. Can you give me a little internet boost?",
    "Whoops, Sir! I'm offline. Could you plug me back in?",
    "Sir, I'm feeling disconnected. Could you connect me to the internet?",
    "Yikes, Sir! No internet. Can you help me get back online?",
    "Oops, Sir! I'm offline. Could you connect me to the web?",
    "Sir, I'm not operational. Could you hook me up to the internet?",
    "Uh-oh, Sir! I'm offline. Could you reconnect me?",
    "Whoops, Sir! No internet. Can you give me a little boost?",
    "Sir, I'm feeling a bit lonely without the internet. Could you connect me?",
    "Yikes, Sir! I'm offline. Could you plug me back into the web?",
    "Oops, Sir! I'm not operational. Can you connect me to the internet?",
    "Sir, I'm feeling disconnected. Could you give me a little internet magic?",
    "Uh-oh, Sir! No internet. Can you reconnect me?",
    "Whoops, Sir! I'm offline. Could you hook me up?",
    "Sir, I'm not operational. Could you connect me to the web?",
    "Yikes, Sir! I'm offline. Can you help me get back online?",
    "Oops, Sir! No internet. Could you connect me?",
    "Sir, I'm feeling a bit lost without the internet. Could you plug me back in?",
    "Uh-oh, Sir! I'm offline. Could you reconnect me to the web?",
    "Whoops, Sir! No internet. Can you give me a little boost?",
    "Sir, I'm not operational. Could you connect me to the internet?",
    "Yikes, Sir! I'm offline. Can you hook me up?",
    "Oops, Sir! No internet. Could you reconnect me?",
    "Sir, I'm feeling disconnected. Could you connect me to the web?",
    "Uh-oh, Sir! I'm offline. Could you plug me back into the internet?",
    "Whoops, Sir! No internet. Can you help me get back online?",
    "Sir, I'm not operational. Could you connect me to the web?",
    "Yikes, Sir! I'm offline. Can you reconnect me?",
    "Oops, Sir! No internet. Could you hook me up?",
    "Sir, I'm feeling a bit lonely without the internet. Could you connect me?",
    "Uh-oh, Sir! I'm offline. Could you plug me back in?",
    "Whoops, Sir! No internet. Can you connect me to the web?",
    "Sir, I'm not operational. Could you help me get back online?",
    "Yikes, Sir! I'm offline. Could you reconnect me to the internet?",
    "Oops, Sir! No internet. Could you give me a little boost?",
    "Sir, I'm feeling disconnected. Could you connect me to the web?",
    "Uh-oh, Sir! I'm offline. Could you plug me back into the internet?",
    "Whoops, Sir! No internet. Can you reconnect me?",
    "Sir, I'm not operational. Could you help me get back online?",
    "Yikes, Sir! I'm offline. Could you connect me to the web?",
    "Oops, Sir! No internet. Could you hook me up?",
    "Sir, I'm feeling a bit lonely without the internet. Could you reconnect me?",
    "Uh-oh, Sir! I'm offline. Could you plug me back in?",
    "Whoops, Sir! No internet. Can you connect me to the web?",
    "Sir, I'm not operational. Could you help me get back online?"
]
