websites = {
    "youtube": "www.youtube.com",
    "facebook": "www.facebook.com",
    "whatsapp": "www.whatsapp.com",
    "github": "www.github.com",
    "aniwatch": "www.aniwatch.me",
    "google": "www.google.com",
    "twitter": "www.twitter.com",
    "instagram": "www.instagram.com",
    "linkedin": "www.linkedin.com",
    "reddit": "www.reddit.com",
    "amazon": "www.amazon.com",
    "netflix": "www.netflix.com",
    "wikipedia": "www.wikipedia.org",
    "stack overflow": "www.stackoverflow.com",
    "quora": "www.quora.com",
    "twitch": "www.twitch.tv",
    "pinterest": "www.pinterest.com",
    "snapchat": "www.snapchat.com",
    "tiktok": "www.tiktok.com",
    "dropbox": "www.dropbox.com",
    "spotify": "www.spotify.com",
    "slack": "www.slack.com",
    "zoom": "www.zoom.us",
    "microsoft": "www.microsoft.com",
    "apple": "www.apple.com",
    "bbc": "www.bbc.com",
    "cnn": "www.cnn.com",
    "yahoo": "www.yahoo.com",
    "bing": "www.bing.com",
    "ebay": "www.ebay.com",
    "paypal": "www.paypal.com",
    "wordpress": "www.wordpress.com",
    "medium": "www.medium.com",
    "hacker news": "www.news.ycombinator.com",
    "imdb": "www.imdb.com",
    "flickr": "www.flickr.com",
    "vimeo": "www.vimeo.com",
    "airbnb": "www.airbnb.com",
    "uber": "www.uber.com",
    "lyft": "www.lyft.com",
    "coursera": "www.coursera.org",
    "udemy": "www.udemy.com",
    "khanacademy": "www.khanacademy.org",
    "codepen": "www.codepen.io",
    "jsfiddle": "www.jsfiddle.net",
    "codecademy": "www.codecademy.com",
    "dribbble": "www.dribbble.com",
    "behance": "www.behance.net",
    "canva": "www.canva.com",
    "trello": "www.trello.com",
    "asana": "www.asana.com",
    "notion": "www.notion.so",
    "evernote": "www.evernote.com",
    "mashable": "www.mashable.com",
    "techcrunch": "www.techcrunch.com",
    "the verge": "www.theverge.com",
    "wired": "www.wired.com",
    "gizmodo": "www.gizmodo.com",
    "engadget": "www.engadget.com",
    "ars technica": "www.arstechnica.com",
    "cnet": "www.cnet.com",
    "zdnet": "www.zdnet.com",
    "digital trends": "www.digitaltrends.com",
    "techradar": "www.techradar.com",
    "android central": "www.androidcentral.com",
    "imore": "www.imore.com",
    "macrumors": "www.macrumors.com",
    "9to5mac": "www.9to5mac.com",
    "venturebeat": "www.venturebeat.com",
    "business insider": "www.businessinsider.com",
    "forbes": "www.forbes.com",
    "bloomberg": "www.bloomberg.com",
    "the wall street journal": "www.wsj.com",
    "financial times": "www.ft.com",
    "the economist": "www.economist.com",
    "fortune": "www.fortune.com",
    "marketwatch": "www.marketwatch.com",
    "reuters": "www.reuters.com",
    "cnbc": "www.cnbc.com",
    "nbc news": "www.nbcnews.com",
    "abc news": "www.abcnews.go.com",
    "cbs news": "www.cbsnews.com",
    "fox news": "www.foxnews.com",
    "the guardian": "www.theguardian.com",
    "the new york times": "www.nytimes.com",
    "the washington post": "www.washingtonpost.com",
    "los angeles times": "www.latimes.com",
    "usa today": "www.usatoday.com",
    "npr": "www.npr.org",
    "al jazeera": "www.aljazeera.com",
    "buzzfeed": "www.buzzfeed.com",
    "vice": "www.vice.com",
    "vox": "www.vox.com",
    "huffpost": "www.huffpost.com",
    "salon": "www.salon.com",
    "slate": "www.slate.com",
    "the atlantic": "www.theatlantic.com",
    "politico": "www.politico.com",
    "new york post": "www.nypost.com",
    "the hill": "www.thehill.com",
    "the drudge report": "www.drudgereport.com",
    "breitbart": "www.breitbart.com",
    "daily kos": "www.dailykos.com",
    "mother jones": "www.motherjones.com",
    "propublica": "www.propublica.org",
    "the intercept": "www.theintercept.com",
    "democracy now!": "www.democracynow.org",
    "the daily beast": "www.thedailybeast.com",
    "the week": "www.theweek.com",
    "newsweek": "www.newsweek.com",
    "time": "www.time.com",
    "people": "www.people.com",
    "entertainment weekly": "www.ew.com",
    "rolling stone": "www.rollingstone.com",
    "billboard": "www.billboard.com",
    "pitchfork": "www.pitchfork.com",
    "nme": "www.nme.com",
    "variety": "www.variety.com",
    "the hollywood reporter": "www.hollywoodreporter.com",
    "deadline": "www.deadline.com",
    "e! online": "www.eonline.com",
    "mtv": "www.mtv.com",
    "vh1": "www.vh1.com",
    "bravo tv": "www.bravotv.com",
    "syfy": "www.syfy.com",
    "amc": "www.amc.com",
    "hbo": "www.hbo.com",
    "showtime": "www.sho.com",
    "starz": "www.starz.com",
    "cinemax": "www.cinemax.com",
    "paramount+": "www.paramountplus.com",
    "peacock": "www.peacocktv.com",
    "disney+": "www.disneyplus.com",
    "hulu": "www.hulu.com",
    "prime video": "www.primevideo.com",
    "apple tv+": "www.tv.apple.com",
    "crunchyroll": "www.crunchyroll.com",
    "funimation": "www.funimation.com",
    "vrv": "www.vrv.co",
    "myanimelist": "www.myanimelist.net",
    "anime news network": "www.animenewsnetwork.com",
    "animelab": "www.animelab.com",
    "9anime": "www.9anime.to",
    "gogoanime": "www.gogoanime.ai",
    "kissanime": "www.kissanime.ru",
    "chia-anime": "www.chia-anime.me",
    "animefreak": "www.animefreak.tv",
    "anime-planet": "www.anime-planet.com",
    "anilist": "www.anilist.co",
    "mangadex": "www.mangadex.org",
    "manga rock": "www.mangarock.com",
    "webtoons": "www.webtoons.com",
    "tapas": "www.tapas.io",
    "comixology": "www.comixology.com",
    "marvel": "www.marvel.com",
    "dc": "www.dccomics.com",
    "image comics": "www.imagecomics.com",
    "dark horse": "www.darkhorse.com",
    "idw publishing": "www.idwpublishing.com",
    "boom! studios": "www.boom-studios.com",
    "oni press": "www.onipress.com",
    "archie comics": "www.archiecomics.com",
    "dynamite entertainment": "www.dynamite.com",
    "valiant comics": "www.valiantentertainment.com",
    "viz media": "www.viz.com",
    "tokyopop": "www.tokyopop.com",
    "yen press": "www.yenpress.com",
    "kodansha comics": "www.kodanshacomics.com",
    "seven seas entertainment": "www.sevenseasentertainment.com",
    "crunchyroll manga": "www.crunchyroll.com/comics/manga",
    "shonen jump": "www.viz.com/shonenjump"
}
